# Generated by Django 3.0.3 on 2020-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('type', models.TextField()),
                ('date', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
