# Generated by Django 3.0.3 on 2020-04-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticedata',
            old_name='text',
            new_name='number',
        ),
    ]
