# Generated by Django 3.0.3 on 2020-04-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_data', '0002_auto_20200426_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticedata',
            name='number',
        ),
    ]
