# Generated by Django 3.0.3 on 2020-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_data', '0003_remove_noticedata_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticedata',
            name='number',
            field=models.TextField(null=True),
        ),
    ]
