# Generated by Django 3.0.3 on 2020-04-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200426_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portal_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portal_pw',
        ),
    ]
