# Generated by Django 3.0.3 on 2020-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200426_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_login',
            new_name='last_update',
        ),
    ]
