# Generated by Django 3.0.3 on 2020-05-05 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200505_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portal_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='학번을 입력해주세요')]),
        ),
    ]
