# Generated by Django 3.0.3 on 2020-04-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_auto_20200426_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('percentage', models.TextField()),
                ('video0', models.IntegerField()),
                ('video1', models.IntegerField()),
                ('video2', models.IntegerField()),
                ('video3', models.IntegerField()),
                ('video4', models.IntegerField()),
                ('report0', models.IntegerField()),
                ('report1', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
