# Generated by Django 3.0.3 on 2020-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearndata',
            name='reports2watch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='elearndata',
            name='videos2watch',
            field=models.TextField(default=''),
        ),
    ]
