# Generated by Django 3.0.3 on 2020-04-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_data', '0002_auto_20200429_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearndata',
            name='report2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elearndata',
            name='video5',
            field=models.IntegerField(default=0),
        ),
    ]
