# Generated by Django 3.0.3 on 2020-04-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_data', '0004_auto_20200429_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elearndata',
            old_name='reports2watch',
            new_name='reports2do',
        ),
    ]
